### PR TITLE
Replace org.postgresql driver with pgjdbc-ng

### PR DESCRIPTION
**Pull request by mikroskeem**
#2582 

Roadmap:
- [x] Replace org.postgresql driver
- [x] Ensure it works properly (basic usage etc.)
- [x] Implement messaging service
- [x] Even more testing

### CODE REVIEW

**Comment by mikroskeem** [comment]
Does not work at all right now:
```
[16:45:55 ERROR] [luckperms]: Failed to init storage implementation
[16:45:55 ERROR]: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5005ms.
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[16:45:55 ERROR]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
[16:45:55 ERROR]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.init(SqlStorage.java:155)
[16:45:55 ERROR]: 	at me.lucko.luckperms.common.storage.Storage.init(Storage.java:115)
[16:45:55 ERROR]: 	at me.lucko.luckperms.common.storage.StorageFactory.getInstance(StorageFactory.java:88)
[16:45:55 ERROR]: 	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:151)
[16:45:55 ERROR]: 	at me.lucko.luckperms.velocity.LPVelocityBootstrap.onEnable(LPVelocityBootstrap.java:144)
[16:45:55 ERROR]: 	at net.kyori.event.asm.generated.5d306b7c20.LPVelocityBootstrap-onEnable-ProxyInitializeEvent-2.invoke(Unknown Source)
[16:45:55 ERROR]: 	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148)
[16:45:55 ERROR]: 	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107)
[16:45:55 ERROR]: 	at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:139)
[16:45:55 ERROR]: 	at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:120)
[16:45:55 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[16:45:55 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[16:45:55 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[16:45:55 ERROR]: Caused by: java.lang.IllegalStateException: Loaded ProcProvider services is below the required threshold, a class loading issue may exist. Found:
[16:45:55 ERROR]: []
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.system.procs.Procs.load(Procs.java:75)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.system.procs.Procs.<init>(Procs.java:65)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.types.SharedRegistry.lambda$new$0(SharedRegistry.java:118)
[16:45:55 ERROR]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1225)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.types.SharedRegistry.<init>(SharedRegistry.java:116)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.AbstractDataSource.lambda$null$1(AbstractDataSource.java:115)
[16:45:55 ERROR]: 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.AbstractDataSource.lambda$createConnection$2(AbstractDataSource.java:115)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.system.BasicContext.init(BasicContext.java:360)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.PGDirectConnection.init(PGDirectConnection.java:288)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:319)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.AbstractDataSource.createConnection(AbstractDataSource.java:142)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.PGDataSource.getConnection(PGDataSource.java:71)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.pgjdbc.jdbc.PGDataSource.getConnection(PGDataSource.java:63)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.access$100(HikariPool.java:71)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
[16:45:55 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
[16:45:55 ERROR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:45:55 ERROR]: 	... 3 more
```

I suppose this is because of relocation does not support rewriting services yet (`META-INF/services/com.impossibl.postgres.system.procs.ProcProvider` and its contents should be rewritten as well).

**Comment by mikroskeem** [comment]
Right now I solved this using isolated classloader, but now I get another issue with less information this time.

```
[17:07:39 ERROR]: java.util.concurrent.CompletionException: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[17:07:39 ERROR]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:104)
[17:07:39 ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[17:07:39 ERROR]: 	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:185)
[17:07:39 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:07:39 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:07:39 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[17:07:39 ERROR]: Caused by: java.sql.SQLTransientConnectionException: luckperms-hikari - Connection is not available, request timed out after 5000ms.
[17:07:39 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[17:07:39 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[17:07:39 ERROR]: 	at me.lucko.luckperms.lib.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[17:07:39 ERROR]: 	at me.lucko.luckperms.lib.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
[17:07:39 ERROR]: 	at me.lucko.luckperms.common.storage.implementation.sql.connection.hikari.HikariConnectionFactory.getConnection(HikariConnectionFactory.java:151)
[17:07:39 ERROR]: 	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.loadAllGroups(SqlStorage.java:439)
[17:07:39 ERROR]: 	at me.lucko.luckperms.common.storage.Storage.lambda$loadAllGroups$10(Storage.java:195)
[17:07:39 ERROR]: 	at me.lucko.luckperms.common.storage.Storage.lambda$makeFuture$1(Storage.java:99)
[17:07:39 ERROR]: 	... 5 more
```

If anyone has time to help with debugging this, then I'd be grateful. 😄

**Comment by mikroskeem** [comment]
Note: will squash before merging.

**Comment by mikroskeem** [comment]
Not ready yet. Have to debug some messaging-related bugs.

**Comment by lucko** [comment]
Hey - thanks for this!

If the messaging implementation is still pending further testing, do you think it would be worth merging the driver changes anyway?

**Comment by mikroskeem** [comment]
Yes, driver itself works fine.

**Comment by mikroskeem** [comment]
I'm not interested in continuing it this time. Someone else may pick this up.

**Comment by lucko** [comment]
No problem, thank you anyway :)

**Pull request closed without merging**
