### PR TITLE
Update mongodb driver to latest version and save uuid with the new standard (version 4)

### PR DESCRIPTION
**Pull request by SamBolduc**
The mongodb java driver save uuid with the old standard (version 3), now, I force it to save uuid with the new standard (version 4)

### CODE REVIEW

**Comment by lucko** [comment]
Would this change not make the storage incompatible with any existing data saved in a different format?

**Comment by SamBolduc** [comment]
> Thank you for the PR!
> 
> A question though:
> Would this change not make the storage incompatible with any existing data saved in a different format?

Yes, this will break existing ids. It is not possible to transform a uuidv3 to a uuidv4 but an id saved in v3 is unusable since it does not correspond to mojang user's id.

It would be necessary to ensure that version 4 is used only if no data has yet been recorded. Another alternative would be to add an option in the configuration file allowing you to choose the type of id you want.

**Comment by lucko** [comment]
I'm not sure about that - I'm pretty sure the current serialization is working ok - perhaps it would be possible to automatically migrate them to a new format

**Comment by SamBolduc** [comment]
There is the stored _id with uuid saved as v3
image

and there is the stored _id with uuid saved as v4
image

There is my real uuid from mojang:
image

As you can see, the uuid saved as v3 doesn't match the mojang uuid.  This makes it not possible to perform database searches using mojang uuid

**Comment by lucko** [comment]
Thanks for the extra info, I also did a bit of reading about the various UUID types Mongo uses.

A seamless transition is really important here: ideally, we assume that users might not even update all of their servers at the same time, so older versions of LP should be able to continue to function correctly.

So yes, a seamless migration from "current" to "recommended" UUID encoding is important. Otherwise, I'm inclined to just leave things as they are - it does seem to work somewhat ok afterall!

**Pull request closed without merging**
