### PR TITLE
Use HIGH priority for login listeners

### PR DESCRIPTION
**Pull request by sgdc3**
Fixes compatibility with auth plugins

### CODE REVIEW

**Comment by lucko** [comment]
We're listening on LOW to allow auth plugins to change things at LOWEST, but still provide permissions data for plugins listening on NORMAL.

**Comment by sgdc3** [comment]
@lucko ok that makes sense, but isn't better to listen at HIGH in this scenario?

**Comment by lucko** [comment]
No, because then permissions wouldn't be loaded at NORMAL, when most other plugins are listening.

**Comment by sgdc3** [comment]
That also makes sense xD

**Pull request closed without merging**
