### PR TITLE
Update zh-CN locale

### PR DESCRIPTION
**Pull request by EuropeJing**
Now update to the latest version

### CODE REVIEW

**Comment by lucko** [comment]
If it's ok, I'd like to hold off merging this for a bit.

I have a few more messages I want to update. Is that cool with you?

**Comment by lucko** [comment]
https://github.com/lucko/LuckPerms/commit/a14a4161932ffcc008189ae1cad1227bbaae1502#diff-42a222e4e779874fe6eb938048e4cb0f

Quite a big change, but it should be the last one for a while 🤞

**Comment by EuropeJing** [comment]
No problem, it 's nice to help you.😄

**Comment by EuropeJing** [comment]
@lucko I have updated the locale file.
Your file changes are big, but I have finished.🎉

**Comment by lucko** [comment]
Thank you!

**Pull request merged**
