### PR TITLE
Implement issue and pull request-templates

### PR DESCRIPTION
**Pull request by Andre601**
Even tho the commit list seems quite long, is this only a PR to add issue-templates and a PR-template.

Examples of those (including their raw format) can be found under the following links:
- Feature Request: https://github.com/Andre601/LuckPerms/issues/9
- Question: https://github.com/Andre601/LuckPerms/issues/8
- Bug Report: https://github.com/Andre601/LuckPerms/issues/7
- Pull Request: https://github.com/Andre601/LuckPerms/pull/6

The main reason why templates should be implemented is to make managing issues and PRs easier due to having a consistent look,
Those templates would also auto-assign a label corresponding to the actual type of issue (might need a change if labels are different).

### CODE REVIEW

**Comment by BrainStone** [comment]
That would be much apprechiated.

**Comment by Setraxis** [comment]
To much changes in 1 commit. Do only 1 clean pullrequest instead of 1716 changes in 1 pullrequest in the same file.

**Comment by Andre601** [comment]
> To much changes in 1 commit. Do only 1 clean pullrequest instead of 1716 changes in 1 pullrequest in the same file.

Please do me a favour and **read** the PR first before commenting useles stuff as I give a reason on why this PR has so many commits:
> Even tho the commit list seems quite long, is this only a PR to add issue-templates and a PR-template.

**Comment by Setraxis** [comment]
@lucko i will bring a clean pullrequest. close this

**Comment by Andre601** [comment]
I will close this due to above *"reasons"*.
Like mentioned in my previous comment did I consider remaking this PR, but your general attitude @Setraxis is not making this happen.
Why your behaviour is bad and should be changed can you read in [this comment](https://github.com/lucko/LuckPerms/pull/1852#issuecomment-562024146) that I made.
LuckPerms is an open-source project. And those are about embracing other people to contribute and to give __positive__ feedback.
I really hope your attitude will change as such behaviour is really counter-productive towards others.

**Comment by Andre601** [comment]
Re-open this as @lucko requested it

**Comment by lucko** [comment]
> To much changes in 1 commit. Do only 1 clean pullrequest instead of 1716 changes in 1 pullrequest in the same file.

Copying my reply from the other thread: The number of commits on a PR doesn't matter, because they all get squashed together when the PR is merged anyway. The overall changes (under the "Files changed" tab on GitHub) is all that matters really.

> @lucko i will bring a clean pullrequest. close this

That is absolutely no reason to create a new PR.

**Comment by lucko** [comment]
And regarding the PR more generally, sorry I've let it sit for a while. 

I'm still deciding exactly how I want issue templates to work out - I'm really not a fan of them on other repos - want to make sure that if they do get added to this repository, they're good!

**Comment by Andre601** [comment]
Feel free to suggest any changes in terms of style and behaviour.
I have linked the current style of the templates (both actual and raw view) in my PR comment at the top, so that you can see it and provide feedback (or just commit your own)

**Comment by BrainStone** [comment]
And even if there were 200 commits @Setraxis what difference would it make?

**Comment by Tobi406** [comment]
Just some idea:

Maybe have a (outcommented) section that lists *very* common errors as such #952.

**Comment by Andre601** [comment]
How should I add those tho?
I agree it would perhaps help, but I think the template shouldn't be too much at once, even if it is just hidden comments.

**Comment by Tobi406** [comment]
Maybe we can also link to these from the FAQ wiki page?

**Comment by Andre601** [comment]
Would be an option

**Comment by Andre601** [comment]
I've added a comment about checking the FAQ in the bug report template.
The question template already links to it and the feature request template seems not worth to add it.

**Comment by Haveyougonemad** [comment]
WHAT

**Comment by Andre601** [comment]
Should we consider adding a `config.yml` too for customisation of the template-picker?

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by lucko** [comment]
Looks like this needs rebasing ;)

**Comment by Andre601** [comment]
> Looks like this needs rebasing ;)

Should be resolved. Double check for safety.

**Comment by Andre601** [comment]
[config]: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

Should this PR maybe also include a [config.yml][config] for the template selection?

**Pull request closed without merging**
